name: join-issue
channels:
  - conda-forge
  - r
dependencies:
  - python
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - plotly
  - pip
  - Flask
  - sqlalchemy
  - flask-sqlalchemy
  - pymysql
  - nbformat
  - nbconvert
  - jupyter
  - jupyter_client
  - rpy2
  - h5py
  - pip:  
    - sklearn
    - qgrid
    - clustergrammer-widget
    - matplotlib-venn
